Read CSV Files
CSV Files :
> A simple way to store big data sets is to use CSV files (comma separated
files).
> CSV files contains plain text and is a well know format that can be read
by everyone including Pandas.

In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"

csv_1 = pd.read_csv(url)

csv_1

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
3,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
4,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
96,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
97,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
98,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
99,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [6]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_2 = pd.read_csv(url,nrows=1)
csv_2

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

In [7]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_3 = pd.read_csv(url,usecols=["Company"])
csv_3

                            Company
0                   Rasmussen Group
1                       Vega-Gentry
2                     Murillo-Perry
3   Dominguez, Mcmillan and Donovan
4          Martin, Lang and Andrade
..                              ...
95                        Carey LLC
96            Ware, Burns and Oneal
97                    Schmitt-Jones
98               Fitzgerald-Harrell
99               Le, Nash and Cross

[100 rows x 1 columns]

In [9]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_4 = pd.read_csv(url,usecols=["Phone 1","Phone 2"])
csv_4

                   Phone 1                 Phone 2
0             229.077.5154        397.884.0519x718
1               5153435776        686-620-1820x944
2          +1-539-402-0259     (496)978-3969x58947
3   001-808-617-6467x12895         +1-813-324-8756
4   001-234-203-0635x76146   001-199-446-3860x3486
..                     ...                     ...
95     (188)169-1674x58692    001-841-293-3519x614
96         +1-846-706-2218            605.413.3198
97    +1-753-067-8419x7170   +1-632-666-7507x92121
98           (530)311-9786  001-869-452-0943x12424
99           (753)813-6941            783.639.1472

[100 rows x 2 columns]

In [10]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_5 = pd.read_csv(url,usecols=[0,3])
csv_5

    Index Last Name
0       1    Baxter
1       2    Lozano
2       3     Berry
3       4     Olsen
4       5    Bender
..    ...       ...
95     96     Greer
96     97  Atkinson
97     98    Guerra
98     99    Farmer
99    100    Haynes

[100 rows x 2 columns]

In [11]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_5 = pd.read_csv(url,skiprows=[1,2])
csv_5

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
1,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
2,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-234-203-0635x76146,001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
3,6,2d08FB17EE273F4,Aimee,Downs,Steele Group,Chavezborough,Bosnia and Herzegovina,(283)437-3886x88321,999-728-1637,louis27@gilbert.com,2020-02-25,http://www.berger.net/
4,7,EA4d384DfDbBf77,Darren,Peck,"Lester, Woodard and Mitchell",Lake Ana,Pitcairn Islands,(496)452-6181x3291,+1-247-266-0963x4995,tgates@cantrell.com,2021-08-24,https://www.le.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
93,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
94,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
95,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
96,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
97,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [12]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_4 = pd.read_csv(url,index_col=["Phone 1"])
csv_4

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 2,Email,Subscription Date,Website
Phone 1,,,,,,,,,,,
229.077.5154,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
5153435776,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
+1-539-402-0259,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
001-808-617-6467x12895,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
001-234-203-0635x76146,5,053d585Ab6b3159,Joanna,Bender,"Martin, Lang and Andrade",West Priscilla,Slovakia (Slovak Republic),001-199-446-3860x3486,colinalvarado@miles.net,2021-04-17,https://goodwin-ingram.com/
...,...,...,...,...,...,...,...,...,...,...,...
(188)169-1674x58692,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
+1-846-706-2218,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
+1-753-067-8419x7170,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
(530)311-9786,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
(753)813-6941,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/

In [23]:
url = "https://raw.githubusercontent.com/pprritthhvvi/CSI-Data-Engineering/main/Week-1-Python-Basics/customers-100.csv"
csv_5 = pd.read_csv(url, header = None)
csv_5

,0,1,2,3,4,5,6,7,8,9,10,11
0,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
1,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
2,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
3,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/
4,4,5Cef8BFA16c5e3c,Linda,Olsen,"Dominguez, Mcmillan and Donovan",Bensonview,Dominican Republic,001-808-617-6467x12895,+1-813-324-8756,stanleyblackwell@benson.org,2020-06-02,http://www.good-lyons.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
96,96,cb8E23e48d22Eae,Karl,Greer,Carey LLC,East Richard,Guyana,(188)169-1674x58692,001-841-293-3519x614,hhart@jensen.com,2022-01-30,http://hayes-perez.com/
97,97,CeD220bdAaCfaDf,Lynn,Atkinson,"Ware, Burns and Oneal",New Bradview,Sri Lanka,+1-846-706-2218,605.413.3198,vkemp@ferrell.com,2021-07-10,https://novak-allison.com/
98,98,28CDbC0dFe4b1Db,Fred,Guerra,Schmitt-Jones,Ortegaland,Solomon Islands,+1-753-067-8419x7170,+1-632-666-7507x92121,swagner@kane.org,2021-09-18,https://www.ross.com/
99,99,c23d1D9EE8DEB0A,Yvonne,Farmer,Fitzgerald-Harrell,Lake Elijahview,Aruba,(530)311-9786,001-869-452-0943x12424,mccarthystephen@horn-green.biz,2021-08-11,http://watkins.info/
100,100,2354a0E336A91A1,Clarence,Haynes,"Le, Nash and Cross",Judymouth,Honduras,(753)813-6941,783.639.1472,colleen91@faulkner.biz,2020-03-11,http://www.hatfield-saunders.net/