Introduction to Pandas

What is Pandas?

A powerful library for data manipulation and analysis in Python. Built on top of NumPy, provides data structures like Series and DataFrame.

Why use Pandas?
. Easy data cleaning and transformation.
· Efficient handling of large datasets.
. Integration with other Python libraries like Matplotlib and Seaborn for visualization.

Key Data Structures in Pandas
> Series(1D), 
> DataFrame(2D)

In [3]:
import pandas as pd
s = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
df = pd.DataFrame({"names": ["Prithvi","Rohan", "Shubham"],"marks": [100, 53, 45]})
df

     names  marks
0  Prithvi    100
1    Rohan     53
2  Shubham     45

In [6]:
df = pd.read_csv("employees.csv")
df

   id     name  salary       dept
0   1   manish   50000         IT
1   2   vikash   60000      sales
2   3  raushan   70000  marketing
3   4   mukesh   80000         IT
4   5   pritam   90000      sales
5   6   nikita   45000  marketing
6   7   ragini   55000  marketing
7   8   rakesh  100000         IT
8   9   aditya   65000         IT
9  10    rahul   50000  marketing

In [7]:
df.head()

   id     name  salary       dept
0   1   manish   50000         IT
1   2   vikash   60000      sales
2   3  raushan   70000  marketing
3   4   mukesh   80000         IT
4   5   pritam   90000      sales

In [8]:
df.tail()

   id    name  salary       dept
5   6  nikita   45000  marketing
6   7  ragini   55000  marketing
7   8  rakesh  100000         IT
8   9  aditya   65000         IT
9  10   rahul   50000  marketing

In [9]:
df.describe()

             id         salary
count  10.00000      10.000000
mean    5.50000   66500.000000
std     3.02765   18416.478129
min     1.00000   45000.000000
25%     3.25000   51250.000000
50%     5.50000   62500.000000
75%     7.75000   77500.000000
max    10.00000  100000.000000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      10 non-null     int64
 1   name    10 non-null     object
 2   salary  10 non-null     int64
 3   dept    10 non-null     object
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [12]:
# data selection
type(df["id"])

pandas.core.series.Series

In [13]:
df.iloc[0]

id             1
name      manish
salary     50000
dept          IT
Name: 0, dtype: object

In [14]:
type(df.iloc[0])

pandas.core.series.Series