Grouping Data with Pandas

. group by object

. basic Aggregate functions

· subgrouping

. agg() : Calculate multiple summary statistics for each group at once.

. apply() : Run a totally custom and complex function on each group.

. transform() : Perform a group calculation and return a result with the same shape as your original data.

· filter() : Keep or remove entire groups based on a condition.

In [1]:
import pandas as pd

data = {
    "Name": ["Sneha","Pooja","Amit","Rohit","Meena",
             "Rahul","Ravi","Neha","Tina","Arjun",
             "Simran","Manish","Ankit","Priya","Karan"],

    "Department": ["IT","Marketing","HR","Marketing","Finance",
                   "IT","HR","HR","Marketing","Finance",
                   "IT","IT","Marketing","Finance","Finance"],

    "Salary": [78000,50000,45000,47000,68000,
               85000,48000,52000,53000,75000,
               80000,82000,55000,60000,72000]
}

df = pd.DataFrame(data)

print("Original Data")
print(df)

print("\nGroupBy")

for department, group in df.groupby("Department"):
    print("\nDepartment:", department)
    print(group)

print("\nSum")
print(df.groupby("Department")["Salary"].sum())

print("\nMean")
print(df.groupby("Department")["Salary"].mean())

print("\nMin")
print(df.groupby("Department")["Salary"].min())

print("\nMax")
print(df.groupby("Department")["Salary"].max())

print("\nCount")
print(df.groupby("Department")["Salary"].count())

print("\nAggregate Functions")
print(df.groupby("Department")["Salary"].agg(["sum","mean","min","max","count"]))

print("\nCustom Aggregate")
print(df.groupby("Department").agg(
    Total_Salary=("Salary","sum"),
    Average_Salary=("Salary","mean"),
    Minimum_Salary=("Salary","min"),
    Maximum_Salary=("Salary","max"),
    Employee_Count=("Salary","count")
))

print("\nSort by Total Salary")
print(df.groupby("Department")["Salary"].sum().sort_values(ascending=False))

print("\nFilter (Average Salary > 60000)")
print(df.groupby("Department").filter(lambda x: x["Salary"].mean() > 60000))

print("\nTransform")
df["Department_Average"] = df.groupby("Department")["Salary"].transform("mean")
print(df)

print("\nApply")
print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))

print("\nMultiple GroupBy")
print(df.groupby(["Department","Name"])["Salary"].sum())

print("\nDescribe")
print(df.groupby("Department")["Salary"].describe())

Original Data
      Name Department  Salary
0    Sneha         IT   78000
1    Pooja  Marketing   50000
2     Amit         HR   45000
3    Rohit  Marketing   47000
4    Meena    Finance   68000
5    Rahul         IT   85000
6     Ravi         HR   48000
7     Neha         HR   52000
8     Tina  Marketing   53000
9    Arjun    Finance   75000
10  Simran         IT   80000
11  Manish         IT   82000
12   Ankit  Marketing   55000
13   Priya    Finance   60000
14   Karan    Finance   72000

GroupBy

Department: Finance
     Name Department  Salary
4   Meena    Finance   68000
9   Arjun    Finance   75000
13  Priya    Finance   60000
14  Karan    Finance   72000

Department: HR
   Name Department  Salary
2  Amit         HR   45000
6  Ravi         HR   48000
7  Neha         HR   52000

Department: IT
      Name Department  Salary
0    Sneha         IT   78000
5    Rahul         IT   85000
10  Simran         IT   80000
11  Manish         IT   82000

Department: Marketing
     Name Department  Salary
1   Pooja  Marketing   50000
3   Rohit  Marketing   47000
8    Tina  Marketing   53000
12  Ankit  Marketing   55000

Sum
Department
Finance      275000
HR           145000
IT           325000
Marketing    205000
Name: Salary, dtype: int64

Mean
Department
Finance      68750.000000
HR           48333.333333
IT           81250.000000
Marketing    51250.000000
Name: Salary, dtype: float64

Min
Department
Finance      60000
HR           45000
IT           78000
Marketing    47000
Name: Salary, dtype: int64

Max
Department
Finance      75000
HR           52000
IT           85000
Marketing    55000
Name: Salary, dtype: int64

Count
Department
Finance      4
HR           3
IT           4
Marketing    4
Name: Salary, dtype: int64

Aggregate Functions
               sum          mean    min    max  count
Department
Finance     275000  68750.000000  60000  75000      4
HR          145000  48333.333333  45000  52000      3
IT          325000  81250.000000  78000  85000      4
Marketing   205000  51250.000000  47000  55000      4

Custom Aggregate
            Total_Salary  Average_Salary  Minimum_Salary  Maximum_Salary  \
Department
Finance           275000    68750.000000           60000           75000
HR                145000    48333.333333           45000           52000
IT                325000    81250.000000           78000           85000
Marketing         205000    51250.000000           47000           55000

            Employee_Count
Department
Finance                  4
HR                       3
IT                       4
Marketing                4

Sort by Total Salary
Department
IT           325000
Finance      275000
Marketing    205000
HR           145000
Name: Salary, dtype: int64

Filter (Average Salary > 60000)
      Name Department  Salary
0    Sneha         IT   78000
4    Meena    Finance   68000
5    Rahul         IT   85000
9    Arjun    Finance   75000
10  Simran         IT   80000
11  Manish         IT   82000
13   Priya    Finance   60000
14   Karan    Finance   72000

Transform
      Name Department  Salary  Department_Average
0    Sneha         IT   78000        81250.000000
1    Pooja  Marketing   50000        51250.000000
2     Amit         HR   45000        48333.333333
3    Rohit  Marketing   47000        51250.000000
4    Meena    Finance   68000        68750.000000
5    Rahul         IT   85000        81250.000000
6     Ravi         HR   48000        48333.333333
7     Neha         HR   52000        48333.333333
8     Tina  Marketing   53000        51250.000000
9    Arjun    Finance   75000        68750.000000
10  Simran         IT   80000        81250.000000
11  Manish         IT   82000        81250.000000
12   Ankit  Marketing   55000        51250.000000
13   Priya    Finance   60000        68750.000000
14   Karan    Finance   72000        68750.000000

Apply
                Name Department  Salary  Department_Average
Department
Finance    9   Arjun    Finance   75000        68750.000000
HR         7    Neha         HR   52000        48333.333333
IT         5   Rahul         IT   85000        81250.000000
Marketing  12  Ankit  Marketing   55000        51250.000000

Multiple GroupBy
Department  Name
Finance     Arjun     75000
            Karan     72000
            Meena     68000
            Priya     60000
HR          Amit      45000
            Neha      52000
            Ravi      48000
IT          Manish    82000
            Rahul     85000
            Simran    80000
            Sneha     78000
Marketing   Ankit     55000
            Pooja     50000
            Rohit     47000
            Tina      53000
Name: Salary, dtype: int64

Describe
            count          mean          std      min      25%      50%  \
Department
Finance       4.0  68750.000000  6500.000000  60000.0  66000.0  70000.0
HR            3.0  48333.333333  3511.884584  45000.0  46500.0  48000.0
IT            4.0  81250.000000  2986.078811  78000.0  79500.0  81000.0
Marketing     4.0  51250.000000  3500.000000  47000.0  49250.0  51500.0

                75%      max
Department
Finance     72750.0  75000.0
HR          50000.0  52000.0
IT          82750.0  85000.0
Marketing   53500.0  55000.0

C:\Users\HP\AppData\Local\Temp\ipykernel_24976\1921159764.py:66: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))

In [4]:
import pandas as pd

df = pd.read_csv("employees.csv")
print(df.head())

   id     name  salary       dept
0   1   manish   50000         IT
1   2   vikash   60000      sales
2   3  raushan   70000  marketing
3   4   mukesh   80000         IT
4   5   pritam   90000      sales

In [6]:
df['dept'].unique()

array(['IT', 'sales', 'marketing'], dtype=object)

In [7]:
df.groupby(by='dept')

In [8]:
group_object =df.groupby(by='dept')
group_object.groups

{'IT': [0, 3, 7, 8], 'marketing': [2, 5, 6, 9], 'sales': [1, 4]}

In [10]:
group_object.ngroup

In [9]:
group_object.size()

dept
IT           4
marketing    4
sales        2
dtype: int64

In [11]:
for name , data in group_object:
    print(name)
    print(data)

IT
   id    name  salary dept
0   1  manish   50000   IT
3   4  mukesh   80000   IT
7   8  rakesh  100000   IT
8   9  aditya   65000   IT
marketing
   id     name  salary       dept
2   3  raushan   70000  marketing
5   6   nikita   45000  marketing
6   7   ragini   55000  marketing
9  10    rahul   50000  marketing
sales
   id    name  salary   dept
1   2  vikash   60000  sales
4   5  pritam   90000  sales

In [14]:
group_object.get_group('sales')

   id    name  salary   dept
1   2  vikash   60000  sales
4   5  pritam   90000  sales

In [ ]:
df.groupby(by='dept')['salary'].mean()

dept
IT           295000
marketing    220000
sales        150000
Name: salary, dtype: int64

In [22]:
df.groupby(by='dept')['salary'].max()

dept
IT           100000
marketing     70000
sales         90000
Name: salary, dtype: int64

In [ ]:
df.groupby(by='dept')['salary'].min()

dept
IT           50000
marketing    45000
sales        60000
Name: salary, dtype: int64

In [24]:
df.groupby(by='dept')['salary'].sum()

dept
IT           295000
marketing    220000
sales        150000
Name: salary, dtype: int64

In [25]:
df.groupby(by='dept')['salary'].count()

dept
IT           4
marketing    4
sales        2
Name: salary, dtype: int64

In [26]:
df.groupby(by='dept')['salary'].describe()

,count,mean,std,min,25%,50%,75%,max
dept,,,,,,,,
IT,4.0,73750.0,21360.009363,50000.0,61250.0,72500.0,85000.0,100000.0
marketing,4.0,55000.0,10801.234497,45000.0,48750.0,52500.0,58750.0,70000.0
sales,2.0,75000.0,21213.203436,60000.0,67500.0,75000.0,82500.0,90000.0

In [28]:
import pandas as pd

data = {
    "Employee": ["Rahul","Priya","Amit","Neha","Rohit","Sneha","Karan","Pooja","Arjun","Meena"],
    "Department": ["IT","IT","HR","HR","Finance","Finance","IT","HR","Finance","IT"],
    "Salary": [70000,65000,50000,55000,80000,75000,72000,52000,82000,68000],
    "Experience": [3,5,2,4,6,5,4,3,7,2]
}

df = pd.DataFrame(data)

print(df)

print("\nSubgrouping")
print(df.groupby(["Department", "Experience"]).sum(numeric_only=True))

print("\nagg()")
print(df.groupby("Department").agg(
    Total_Salary=("Salary","sum"),
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
    Minimum_Salary=("Salary","min"),
    Employee_Count=("Salary","count")
))

print("\napply()")
print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))

print("\ntransform()")
df["Department_Average"] = df.groupby("Department")["Salary"].transform("mean")
print(df)

print("\nfilter()")
print(df.groupby("Department").filter(lambda x: x["Salary"].mean() > 70000))

  Employee Department  Salary  Experience
0    Rahul         IT   70000           3
1    Priya         IT   65000           5
2     Amit         HR   50000           2
3     Neha         HR   55000           4
4    Rohit    Finance   80000           6
5    Sneha    Finance   75000           5
6    Karan         IT   72000           4
7    Pooja         HR   52000           3
8    Arjun    Finance   82000           7
9    Meena         IT   68000           2

Subgrouping
                       Salary
Department Experience
Finance    5            75000
           6            80000
           7            82000
HR         2            50000
           3            52000
           4            55000
IT         2            68000
           3            70000
           4            72000
           5            65000

agg()
            Total_Salary  Average_Salary  Maximum_Salary  Minimum_Salary  \
Department
Finance           237000    79000.000000           82000           75000
HR                157000    52333.333333           55000           50000
IT                275000    68750.000000           72000           65000

            Employee_Count
Department
Finance                  3
HR                       3
IT                       4

apply()
             Employee Department  Salary  Experience
Department
Finance    8    Arjun    Finance   82000           7
HR         3     Neha         HR   55000           4
IT         6    Karan         IT   72000           4

transform()
  Employee Department  Salary  Experience  Department_Average
0    Rahul         IT   70000           3        68750.000000
1    Priya         IT   65000           5        68750.000000
2     Amit         HR   50000           2        52333.333333
3     Neha         HR   55000           4        52333.333333
4    Rohit    Finance   80000           6        79000.000000
5    Sneha    Finance   75000           5        79000.000000
6    Karan         IT   72000           4        68750.000000
7    Pooja         HR   52000           3        52333.333333
8    Arjun    Finance   82000           7        79000.000000
9    Meena         IT   68000           2        68750.000000

filter()
  Employee Department  Salary  Experience  Department_Average
4    Rohit    Finance   80000           6             79000.0
5    Sneha    Finance   75000           5             79000.0
8    Arjun    Finance   82000           7             79000.0

C:\Users\HP\AppData\Local\Temp\ipykernel_24976\252369353.py:27: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))

In [29]:
import pandas as pd

data = {
    "Employee": ["Rahul","Priya","Amit","Neha","Rohit","Sneha","Karan","Pooja","Arjun","Meena"],
    "Department": ["IT","IT","HR","HR","Finance","Finance","IT","HR","Finance","IT"],
    "Salary": [70000,65000,50000,55000,80000,75000,72000,52000,82000,68000],
    "Experience": [3,5,2,4,6,5,4,3,7,2]
}

df = pd.DataFrame(data)

print("Original Data")
print(df)

print("\nGroupBy")
for dept, group in df.groupby("Department"):
    print("\nDepartment:", dept)
    print(group)

print("\nAggregation")
print(df.groupby("Department")["Salary"].agg(["sum","mean","min","max","count"]))

print("\nTransformation")
df["Average_Salary"] = df.groupby("Department")["Salary"].transform("mean")
print(df)

print("\nFiltration")
print(df.groupby("Department").filter(lambda x: x["Salary"].mean() > 70000))

print("\nApply")
print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))

print("\nSubgroups")
print(df.groupby(["Department","Experience"])["Salary"].sum())

Original Data
  Employee Department  Salary  Experience
0    Rahul         IT   70000           3
1    Priya         IT   65000           5
2     Amit         HR   50000           2
3     Neha         HR   55000           4
4    Rohit    Finance   80000           6
5    Sneha    Finance   75000           5
6    Karan         IT   72000           4
7    Pooja         HR   52000           3
8    Arjun    Finance   82000           7
9    Meena         IT   68000           2

GroupBy

Department: Finance
  Employee Department  Salary  Experience
4    Rohit    Finance   80000           6
5    Sneha    Finance   75000           5
8    Arjun    Finance   82000           7

Department: HR
  Employee Department  Salary  Experience
2     Amit         HR   50000           2
3     Neha         HR   55000           4
7    Pooja         HR   52000           3

Department: IT
  Employee Department  Salary  Experience
0    Rahul         IT   70000           3
1    Priya         IT   65000           5
6    Karan         IT   72000           4
9    Meena         IT   68000           2

Aggregation
               sum          mean    min    max  count
Department
Finance     237000  79000.000000  75000  82000      3
HR          157000  52333.333333  50000  55000      3
IT          275000  68750.000000  65000  72000      4

Transformation
  Employee Department  Salary  Experience  Average_Salary
0    Rahul         IT   70000           3    68750.000000
1    Priya         IT   65000           5    68750.000000
2     Amit         HR   50000           2    52333.333333
3     Neha         HR   55000           4    52333.333333
4    Rohit    Finance   80000           6    79000.000000
5    Sneha    Finance   75000           5    79000.000000
6    Karan         IT   72000           4    68750.000000
7    Pooja         HR   52000           3    52333.333333
8    Arjun    Finance   82000           7    79000.000000
9    Meena         IT   68000           2    68750.000000

Filtration
  Employee Department  Salary  Experience  Average_Salary
4    Rohit    Finance   80000           6         79000.0
5    Sneha    Finance   75000           5         79000.0
8    Arjun    Finance   82000           7         79000.0

Apply
             Employee Department  Salary  Experience  Average_Salary
Department
Finance    8    Arjun    Finance   82000           7    79000.000000
HR         3     Neha         HR   55000           4    52333.333333
IT         6    Karan         IT   72000           4    68750.000000

Subgroups
Department  Experience
Finance     5             75000
            6             80000
            7             82000
HR          2             50000
            3             52000
            4             55000
IT          2             68000
            3             70000
            4             72000
            5             65000
Name: Salary, dtype: int64

C:\Users\HP\AppData\Local\Temp\ipykernel_24976\2670408436.py:31: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  print(df.groupby("Department").apply(lambda x: x.nlargest(1, "Salary")))